baseURL = "https://peterv.net/"
languageCode = "en-us"
title = "peterv!"

[params]
  description = "This is my little slice of the web."
  author = "Peter Vaiciulis"
  github = "https://github.com/p5quared"
  email = "petervaiciulis@gmail.com"

[menu]
  [[menu.main]]
    name = "reading"
    url = "/reading/"
    weight = 1
  [[menu.main]]
    name = "posts"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = false

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]
